config/routes.rb
Rails.application.routes.draw do
  resources :intervencions
  resources :plantacions
  resources :parcelas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/intervencion.rb
class Intervencion < ApplicationRecord
  belongs_to :plantacion
end

app/models/parcela.rb
class Parcela < ApplicationRecord
    has_many :plantacions, dependent: :destroy
end

app/models/plantacion.rb
class Plantacion < ApplicationRecord
  belongs_to :parcela
  has_many :intervencions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/intervencions_controller.rb
class IntervencionsController < ApplicationController
  before_action :set_intervencion, only: [:show, :edit, :update, :destroy]

  # GET /intervencions
  # GET /intervencions.json
  def index
    @intervencions = Intervencion.all
  end

  # GET /intervencions/1
  # GET /intervencions/1.json
  def show
  end

  # GET /intervencions/new
  def new
    @intervencion = Intervencion.new
  end

  # GET /intervencions/1/edit
  def edit
  end

  # POST /intervencions
  # POST /intervencions.json
  def create
    @intervencion = Intervencion.new(intervencion_params)

    respond_to do |format|
      if @intervencion.save
        format.html { redirect_to @intervencion, notice: 'Intervencion was successfully created.' }
        format.json { render :show, status: :created, location: @intervencion }
      else
        format.html { render :new }
        format.json { render json: @intervencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intervencions/1
  # PATCH/PUT /intervencions/1.json
  def update
    respond_to do |format|
      if @intervencion.update(intervencion_params)
        format.html { redirect_to @intervencion, notice: 'Intervencion was successfully updated.' }
        format.json { render :show, status: :ok, location: @intervencion }
      else
        format.html { render :edit }
        format.json { render json: @intervencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intervencions/1
  # DELETE /intervencions/1.json
  def destroy
    @intervencion.destroy
    respond_to do |format|
      format.html { redirect_to intervencions_url, notice: 'Intervencion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervencion
      @intervencion = Intervencion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervencion_params
      params.require(:intervencion).permit(:plantacion_id, :accion)
    end
end

app/controllers/parcelas_controller.rb
class ParcelasController < ApplicationController
  before_action :set_parcela, only: [:show, :edit, :update, :destroy]

  # GET /parcelas
  # GET /parcelas.json
  def index
    @parcelas = Parcela.all
  end

  # GET /parcelas/1
  # GET /parcelas/1.json
  def show
  end

  # GET /parcelas/new
  def new
    @parcela = Parcela.new
  end

  # GET /parcelas/1/edit
  def edit
  end

  # POST /parcelas
  # POST /parcelas.json
  def create
    @parcela = Parcela.new(parcela_params)

    respond_to do |format|
      if @parcela.save
        format.html { redirect_to @parcela, notice: 'Parcela was successfully created.' }
        format.json { render :show, status: :created, location: @parcela }
      else
        format.html { render :new }
        format.json { render json: @parcela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parcelas/1
  # PATCH/PUT /parcelas/1.json
  def update
    respond_to do |format|
      if @parcela.update(parcela_params)
        format.html { redirect_to @parcela, notice: 'Parcela was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcela }
      else
        format.html { render :edit }
        format.json { render json: @parcela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcelas/1
  # DELETE /parcelas/1.json
  def destroy
    @parcela.destroy
    respond_to do |format|
      format.html { redirect_to parcelas_url, notice: 'Parcela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcela
      @parcela = Parcela.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parcela_params
      params.require(:parcela).permit(:nombre, :tipo)
    end
end

app/controllers/plantacions_controller.rb
class PlantacionsController < ApplicationController
  before_action :set_parcela, only: [:new, :create]
  before_action :set_plantacion, only: [:show, :edit, :update, :destroy]
 

  # GET /plantacions
  # GET /plantacions.json
  def index
    @plantacions = Plantacion.all
  end

  # GET /plantacions/1
  # GET /plantacions/1.json
  def show
  end

  # GET /plantacions/new
  def new
    @plantacion = Plantacion.new
  end

  # GET /plantacions/1/edit
  def edit
  end

  # POST /plantacions
  # POST /plantacions.json
  def create
    @plantacion = Plantacion.new(plantacion_params)

    respond_to do |format|
      if @plantacion.save
        format.html { redirect_to @plantacion, notice: 'Plantacion was successfully created.' }
        format.json { render :show, status: :created, location: @plantacion }
      else
        format.html { render :new }
        format.json { render json: @plantacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantacions/1
  # PATCH/PUT /plantacions/1.json
  def update
    respond_to do |format|
      if @plantacion.update(plantacion_params)
        format.html { redirect_to @plantacion, notice: 'Plantacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @plantacion }
      else
        format.html { render :edit }
        format.json { render json: @plantacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantacions/1
  # DELETE /plantacions/1.json
  def destroy
    @plantacion.destroy
    respond_to do |format|
      format.html { redirect_to plantacions_url, notice: 'Plantacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plantacion
      @plantacion = Plantacion.find(params[:id])
    end

    def set_parcela
      @parcela = Parcela.find_by(id: params[:parcela_id]) || Parcela.find(plantacion_params[:parcela_id])
    end

    # Only allow a list of trusted parameters through.
    def plantacion_params
      params.require(:plantacion).permit(:parcela_id, :cultivo, :variedad, :numplantas, :observaciones)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intervencions_helper.rb
module IntervencionsHelper
end

app/helpers/parcelas_helper.rb
module ParcelasHelper
end

app/helpers/plantacions_helper.rb
module PlantacionsHelper
end

app/views/intervencions/_form.html.erb
<%= form_with(model: intervencion, local: true) do |form| %>
  <% if intervencion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervencion.errors.count, "error") %> prohibited this intervencion from being saved:</h2>

      <ul>
        <% intervencion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plantacion_id %>
    <%= form.text_field :plantacion_id %>
  </div>

  <div class="field">
    <%= form.label :accion %>
    <%= form.text_field :accion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/intervencions/edit.html.erb
<h1>Editing Intervencion</h1>

<%= render 'form', intervencion: @intervencion %>

<%= link_to 'Show', @intervencion %> |
<%= link_to 'Back', intervencions_path %>

app/views/intervencions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Intervencions</h1>

<table>
  <thead>
    <tr>
      <th>Plantacion</th>
      <th>Accion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intervencions.each do |intervencion| %>
      <tr>
        <td><%= intervencion.plantacion_id %></td>
        <td><%= intervencion.accion %></td>
        <td><%= link_to 'Show', intervencion %></td>
        <td><%= link_to 'Edit', edit_intervencion_path(intervencion) %></td>
        <td><%= link_to 'Destroy', intervencion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervencion', new_intervencion_path %>

app/views/intervencions/new.html.erb
<h1>New Intervencion</h1>

<%= render 'form', intervencion: @intervencion %>

<%= link_to 'Back', intervencions_path %>

app/views/intervencions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plantacion:</strong>
  <%= @intervencion.plantacion_id %>
</p>

<p>
  <strong>Accion:</strong>
  <%= @intervencion.accion %>
</p>

<%= link_to 'Edit', edit_intervencion_path(@intervencion) %> |
<%= link_to 'Back', intervencions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>RegistrosApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/parcelas/_form.html.erb
<%= form_with(model: parcela, local: true) do |form| %>
  <% if parcela.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parcela.errors.count, "error") %> prohibited this parcela from being saved:</h2>

      <ul>
        <% parcela.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parcelas/edit.html.erb
<h1>Editing Parcela</h1>

<%= render 'form', parcela: @parcela %>

<%= link_to 'Show', @parcela %> |
<%= link_to 'Back', parcelas_path %>

app/views/parcelas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parcelas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parcelas.each do |parcela| %>
      <tr>
        <td><%= parcela.nombre %></td>
        <td><%= parcela.tipo %></td>
        <td><%= link_to 'Show', parcela %></td>
        <td><%= link_to 'Edit', edit_parcela_path(parcela) %></td>
        <td><%= link_to 'Destroy', parcela, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parcela', new_parcela_path %>

app/views/parcelas/new.html.erb
<h1>New Parcela</h1>

<%= render 'form', parcela: @parcela %>

<%= link_to 'Back', parcelas_path %>

app/views/parcelas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @parcela.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @parcela.tipo %>
</p>

<%= link_to 'Edit', edit_parcela_path(@parcela) %> |
<%= link_to 'Back', parcelas_path %>
<%= link_to 'nueva plantacion', new_plantacion_path(parcela_id: @parcela)%>

app/views/plantacions/_form.html.erb
<%= form_with(model: plantacion, local: true) do |form| %>
  <% if plantacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plantacion.errors.count, "error") %> prohibited this plantacion from being saved:</h2>

      <ul>
        <% plantacion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= form.hidden_field :parcela_id, value: @plantacion.parcela_id %>
  </div>

  <div class="field">
    <%= form.label :cultivo %>
    <%= form.text_field :cultivo %>
  </div>

  <div class="field">
    <%= form.label :variedad %>
    <%= form.text_field :variedad %>
  </div>

  <div class="field">
    <%= form.label :numplantas %>
    <%= form.text_field :numplantas %>
  </div>

  <div class="field">
    <%= form.label :observaciones %>
    <%= form.text_field :observaciones %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plantacions/edit.html.erb
<h1>Editing Plantacion</h1>

<%= render 'form', plantacion: @plantacion %>

<%= link_to 'Show', @plantacion %> |
<%= link_to 'Back', plantacions_path %>

app/views/plantacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plantacions</h1>

<table>
  <thead>
    <tr>
      <th>Parcela</th>
      <th>Cultivo</th>
      <th>Variedad</th>
      <th>Numplantas</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plantacions.each do |plantacion| %>
      <tr>
        <td><%= plantacion.parcela_id %></td>
        <td><%= plantacion.cultivo %></td>
        <td><%= plantacion.variedad %></td>
        <td><%= plantacion.numplantas %></td>
        <td><%= plantacion.observaciones %></td>
        <td><%= link_to 'Show', plantacion %></td>
        <td><%= link_to 'Edit', edit_plantacion_path(plantacion) %></td>
        <td><%= link_to 'Destroy', plantacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plantacion', new_plantacion_path %>

app/views/plantacions/new.html.erb
<h1>New Plantacion</h1>

<%= render 'form', plantacion: @plantacion %>

<%= link_to 'Back', plantacions_path %>

app/views/plantacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parcela:</strong>
  <%= @plantacion.parcela_id %>
</p>

<p>
  <strong>Cultivo:</strong>
  <%= @plantacion.cultivo %>
</p>

<p>
  <strong>Variedad:</strong>
  <%= @plantacion.variedad %>
</p>

<p>
  <strong>Numplantas:</strong>
  <%= @plantacion.numplantas %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @plantacion.observaciones %>
</p>

<%= link_to 'Edit', edit_plantacion_path(@plantacion) %> |
<%= link_to 'Back', plantacions_path %>